package com.lk.redo.model;

import lombok.ToString;

import java.util.Date;

@ToString
public class SysRedo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.id
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.status
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.biz_type
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private String bizType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.biz_invoke_clazz
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private String bizInvokeClazz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.biz_invoke_method
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private String bizInvokeMethod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.biz_invoke_method_argType
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private String bizInvokeMethodArgtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.biz_invoke_args
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private String bizInvokeArgs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.fail_message
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private String failMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.redo_handler
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private String redoHandler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.auto_redo_able
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private Boolean autoRedoAble;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.auto_redo_limit
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private Integer autoRedoLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.auto_redo_count
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private Integer autoRedoCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.create_time
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.creator
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.update_time
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_redo.updator
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    private String updator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.id
     *
     * @return the value of sys_redo.id
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.id
     *
     * @param id the value for sys_redo.id
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.status
     *
     * @return the value of sys_redo.status
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.status
     *
     * @param status the value for sys_redo.status
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.biz_type
     *
     * @return the value of sys_redo.biz_type
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.biz_type
     *
     * @param bizType the value for sys_redo.biz_type
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.biz_invoke_clazz
     *
     * @return the value of sys_redo.biz_invoke_clazz
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public String getBizInvokeClazz() {
        return bizInvokeClazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.biz_invoke_clazz
     *
     * @param bizInvokeClazz the value for sys_redo.biz_invoke_clazz
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setBizInvokeClazz(String bizInvokeClazz) {
        this.bizInvokeClazz = bizInvokeClazz == null ? null : bizInvokeClazz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.biz_invoke_method
     *
     * @return the value of sys_redo.biz_invoke_method
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public String getBizInvokeMethod() {
        return bizInvokeMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.biz_invoke_method
     *
     * @param bizInvokeMethod the value for sys_redo.biz_invoke_method
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setBizInvokeMethod(String bizInvokeMethod) {
        this.bizInvokeMethod = bizInvokeMethod == null ? null : bizInvokeMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.biz_invoke_method_argType
     *
     * @return the value of sys_redo.biz_invoke_method_argType
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public String getBizInvokeMethodArgtype() {
        return bizInvokeMethodArgtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.biz_invoke_method_argType
     *
     * @param bizInvokeMethodArgtype the value for sys_redo.biz_invoke_method_argType
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setBizInvokeMethodArgtype(String bizInvokeMethodArgtype) {
        this.bizInvokeMethodArgtype = bizInvokeMethodArgtype == null ? null : bizInvokeMethodArgtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.biz_invoke_args
     *
     * @return the value of sys_redo.biz_invoke_args
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public String getBizInvokeArgs() {
        return bizInvokeArgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.biz_invoke_args
     *
     * @param bizInvokeArgs the value for sys_redo.biz_invoke_args
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setBizInvokeArgs(String bizInvokeArgs) {
        this.bizInvokeArgs = bizInvokeArgs == null ? null : bizInvokeArgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.fail_message
     *
     * @return the value of sys_redo.fail_message
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public String getFailMessage() {
        return failMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.fail_message
     *
     * @param failMessage the value for sys_redo.fail_message
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setFailMessage(String failMessage) {
        this.failMessage = failMessage == null ? null : failMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.redo_handler
     *
     * @return the value of sys_redo.redo_handler
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public String getRedoHandler() {
        return redoHandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.redo_handler
     *
     * @param redoHandler the value for sys_redo.redo_handler
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setRedoHandler(String redoHandler) {
        this.redoHandler = redoHandler == null ? null : redoHandler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.auto_redo_able
     *
     * @return the value of sys_redo.auto_redo_able
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public Boolean getAutoRedoAble() {
        return autoRedoAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.auto_redo_able
     *
     * @param autoRedoAble the value for sys_redo.auto_redo_able
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setAutoRedoAble(Boolean autoRedoAble) {
        this.autoRedoAble = autoRedoAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.auto_redo_limit
     *
     * @return the value of sys_redo.auto_redo_limit
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public Integer getAutoRedoLimit() {
        return autoRedoLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.auto_redo_limit
     *
     * @param autoRedoLimit the value for sys_redo.auto_redo_limit
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setAutoRedoLimit(Integer autoRedoLimit) {
        this.autoRedoLimit = autoRedoLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.auto_redo_count
     *
     * @return the value of sys_redo.auto_redo_count
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public Integer getAutoRedoCount() {
        return autoRedoCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.auto_redo_count
     *
     * @param autoRedoCount the value for sys_redo.auto_redo_count
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setAutoRedoCount(Integer autoRedoCount) {
        this.autoRedoCount = autoRedoCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.create_time
     *
     * @return the value of sys_redo.create_time
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.create_time
     *
     * @param createTime the value for sys_redo.create_time
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.creator
     *
     * @return the value of sys_redo.creator
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.creator
     *
     * @param creator the value for sys_redo.creator
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.update_time
     *
     * @return the value of sys_redo.update_time
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.update_time
     *
     * @param updateTime the value for sys_redo.update_time
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_redo.updator
     *
     * @return the value of sys_redo.updator
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_redo.updator
     *
     * @param updator the value for sys_redo.updator
     *
     * @mbg.generated Fri Nov 23 15:31:51 CST 2018
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }
}